packages:
  - apps/*
  - packages/*

allowBuilds:
  core-js: false
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - "@supabase/auth-js@2.110.3"
  - "@supabase/functions-js@2.110.3"
  - "@supabase/postgrest-js@2.110.3"
  - "@supabase/realtime-js@2.110.3"
  - "@supabase/storage-js@2.110.3"
  - "@supabase/supabase-js@2.110.3"
